### ISSUE TITLE
A couple of epubcheck errors on building

### ISSUE THREAD

**Issue by drgrigg** [vr8hub/giovanni-boccaccio_the-decameron_john-payne#3]
Epubcheck gives the following errors:

ERROR(OPF-015): /Users/david/OneDrive/Standard 
Ebooks/TEMP/dist/giovanni-boccaccio_the-decameron_john-payne.epub/epub/text/glossary.xhtml(-1,-1): The property "glossary" 
should not be declared in the OPF file.

ERROR(RSC-012): /Users/david/OneDrive/Standard Ebooks/TEMP/dist/giovanni-boccaccio_the-decameron_john-payne.epub/epub/glossary-search-key-map.xml(24,56): Fragment identifier 
is not defined.

I think the first is a known issue with epubcheck, but the second is correct, there's no such entry as "astonied" in the glossary:

`<search-key-group href="text/glossary.xhtml#astonied">`

**Comment by vr8hub** [comment]
Interestingly, I've only ever gotten the first error when there was another error.

"Astonied" was in the glossary, but it's id was incorrect, so it didn't match the search key. Fixed.
